[package]
name = "gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "leet"
path = "src/main.rs"

[dependencies]
anyhow = "1"
lsp-types = { version = "0.97", features = ["proposed"] }
ropey = "=2.0.0-beta.1"
lsp-wire = { package = "lsp-types", version = "0.95" }
dirs = "6"
futures = "0.3"
gpui-kit = { version = "0.7.1", features = ["tree-sitter-python", "tree-sitter-cpp", "tree-sitter-c", "tree-sitter-go"] }
open = "5"
serde_json = "1"
serde = "1"
url = "2"
practice = { path = "../practice" }
